Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,8 +14,7 @@ inputs:
     required: true
   file_version_id:
     description: 'Enter FILE_VERSION_ID to retrieve a specific backup file.'
-    required: false
-    default: ''
+    required: true
   restore_github_token:
     description: 'Optional: Token to restore workflows (if provided, full mirror restore with workflows).'
     required: false
@@ -102,7 +101,6 @@ runs:
         FILE_VERSION_ID=${{ inputs.fileVersionId }} 
         echo "$FILE_VERSION_ID" > .github/file-security-cache/fileVersionId
         echo "fileVersionId=$FILE_VERSION_ID" >> $GITHUB_ENV
-
 
     - name: Get Activation Token
       id: get_token
@@ -207,8 +205,16 @@ runs:
       if: ${{ (env.CACHE_VALID == 'true' || env.CACHE_VALID == '') && inputs.otp_code != '' }}
       shell: bash
       run: |
+        
+        if [ ! -f ".github/file-security-cache/fileVersionId" ]; then
+          echo "::warning :: The registered file version id could not be found. Please try your operation again by entering the file version id."
+          exit 1
+        else
+          echo "SAVED_FILE_VERSION_ID=$(cat .github/file-security-cache/fileVersionId)" >> $GITHUB_ENV
+        fi
+        
         echo "Retrieving backup file..."
-        RESPONSE=$(curl -s -w "\n%{http_code}" -X GET "https://dev.api.file-security.icredible.com/restore/${{ inputs.file_version_id }}" \
+        RESPONSE=$(curl -s -w "\n%{http_code}" -X GET "https://dev.api.file-security.icredible.com/restore/$SAVED_FILE_VERSION_ID" \
         -H "Authorization: Bearer ${{ env.TOKEN }}" \
         -H "X-Verification-Key: ${{ inputs.otp_code }}" \
         -H "X-Unique-Key: ${{ env.UNIQUE_KEY }}"  -o repo.tar.zst.enc)
