Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,27 +57,29 @@ runs:
 
         echo "TOKEN=$(echo $JSON_BODY | jq -r '.data.token')" >> $GITHUB_ENV
 
-    - name: Request OTP
-      id: request_otp
-      shell: bash
-      run: |
-        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/OTP/Send" \
-        -H "Content-Type: application/json" \
-        -H "Authorization: Bearer $TOKEN" \
-        -d '{
-          "Source": "FileDownload",
-          "OtpGenerationMode": "Number",
-          "Type": "MAIL"
-        }')
-
-        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
-        JSON_BODY=$(echo "$RESPONSE" | head -n -1)
-
-        if [ "$HTTP_STATUS" -ne 200 ]; then
-          echo "OTP request failed" && exit 1
-        fi
-
-        echo "UNIQUE_KEY=$(echo $JSON_BODY | jq -r '.data.uniqueKey')" >> $GITHUB_ENV
+    - name: Request OTP for Restore (If Needed)
+        id: request_otp
+        shell: bash
+        run: |
+          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/OTP/Send" \
+          -H "Content-Type: application/json" \
+          -H "Authorization: Bearer $TOKEN" \
+          -d '{
+            "Source": "FileDownload",
+            "OtpGenerationMode": "Number",
+            "Type": "MAIL"
+          }')
+          echo "Raw API Response: $RESPONSE"
+          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
+          JSON_BODY=$(echo "$RESPONSE" | head -n -1)
+          if [ "$HTTP_STATUS" -ne 200 ]; then
+            echo "Failed to obtain OTP. Response: $RESPONSE"
+            echo "Error: Received HTTP status $HTTP_STATUS"
+            echo "Response: $JSON_BODY"
+            exit 1
+          fi
+          echo "UNIQUE_KEY=$(echo $JSON_BODY | jq -r '.data.uniqueKey')" >> $GITHUB_ENV
+          echo "OTP request sent. Check email for verification code."
 
     - name: Await OTP Input
       uses: step-security/wait-for-secrets@v1
